### ISSUE TITLE
[Question] awesome-chzzk에 기재된 SDK에 문서도 등록해도 될까요?

### ISSUE THREAD

**Issue by gunyu1019** [dokdo2013/awesome-chzzk#14]
파이썬 기반의 [chzzkpy](https://github.com/gunyu1019/chzzkpy) SDK를 개발하고 있는 건유1019입니다.
다름아닌 README에 기재된 [chzzkpy](https://github.com/gunyu1019/chzzkpy)는 개발자 편의를 위해 별도의 한국어와 영어 기반의 문서를 제공하고 있습니다. 
PyPi 외에 SDK 문서 링크를 추가로 기재해도 되는지 여줘뵙고 싶어서 이슈를 올려봅니다. :D

* 한국어 SDK 문서: https://gunyu1019.github.io/chzzkpy/ko/
* 영어 SDK 문서: https://gunyu1019.github.io/chzzkpy/en/

가능하다면, 추가로 Pull Request 올리도록 하겠습니다.

**Comment by dokdo2013** [comment]
@gunyu1019 안녕하세요. 답변이 늦어져 죄송합니다. 추가 링크 첨부가 필요하면 문서 가독성에 영향 없는 범위에서 함께 올려주셔도 무방합니다. PR 올려주시면 확인해서 머지하겠습니다.
